---
- name: "Comprobando si existe carpeta en {{ path_fuse_home }}/bin"
  stat:
    path: "{{ path_fuse_home }}/bin"
  register: result_path_instalation

- name: Detener JBoss Fuse
  command: "sh {{ path_fuse_home }}/bin/stop"
  environment:
     JAVA_HOME: "{{ java_home }}"
  async: true
  register: stopFuse
  when: result_path_instalation.stat.exists